# Generated by Django 4.2.16 on 2026-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_data_assign_math_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtopic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
