# Generated by Django 5.2.17 on 2026-08-19 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auditlog_changes'),
        ('exams', '0005_add_mathtopic_subject_name_unique'),
        ('students', '0004_studentprofile_target_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathtopic',
            options={'ordering': ['subject__name', 'grade_level__order', 'order', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='mathtopic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mathtopic',
            name='grade_level',
            field=models.ForeignKey(blank=True, help_text='The class/Form this topic is taught in, e.g. Form 2. Optional — an unset topic applies across classes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='students.gradelevel'),
        ),
        migrations.AlterUniqueTogether(
            name='mathtopic',
            unique_together={('subject', 'grade_level', 'name')},
        ),
    ]
