# Generated by Django 5.2.17 on 2026-08-24 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0006_mathtopic_grade_level'),
        ('students', '0004_studentprofile_target_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0, help_text='0 = lowest tier, ascending = higher tier')),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(default='shield', help_text='lucide-react icon name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'league_groups',
                'ordering': ['season', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('interval_mode', models.CharField(choices=[('auto', 'Automatic (evenly spaced)'), ('manual', 'Manual (custom bands)')], default='auto', max_length=10)),
                ('band_width', models.PositiveIntegerField(default=10, help_text='Auto mode only: width in percentage points of each band, e.g. 10 -> 0-9, 10-19 ... 90-100.')),
                ('promotion_mode', models.CharField(choices=[('auto', 'Auto-apply promotions'), ('manual', 'Stage for teacher approval')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_exam', models.ForeignKey(help_text='The first individual exam used to place students into their starting band.', on_delete=django.db.models.deletion.CASCADE, related_name='league_seasons_baseline', to='exams.exam')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_seasons', to='students.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_league_seasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'league_seasons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_score', models.FloatField(help_text="Score %% on the season's baseline exam that placed this student.")),
                ('latest_score', models.FloatField(blank=True, help_text='Most recently evaluated score %%.', null=True)),
                ('is_promotion_pending', models.BooleanField(default=False)),
                ('pending_trigger_score', models.FloatField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leagues.leaguegroup')),
                ('latest_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.exam')),
                ('pending_target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_promotions', to='leagues.leaguegroup')),
                ('pending_trigger_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to='students.studentprofile')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leagues.leagueseason')),
            ],
            options={
                'db_table': 'league_memberships',
                'ordering': ['group__order', '-latest_score'],
                'unique_together': {('season', 'student')},
            },
        ),
        migrations.AddField(
            model_name='leaguegroup',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='leagues.leagueseason'),
        ),
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_score', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Staged for Promotion'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_applied', 'Auto-Applied')], default='pending', max_length=15)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_promotions', to=settings.AUTH_USER_MODEL)),
                ('from_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='leagues.leaguegroup')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_events', to='leagues.leaguemembership')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_events', to='leagues.leagueseason')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_promotions', to='students.studentprofile')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='leagues.leaguegroup')),
                ('trigger_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.exam')),
            ],
            options={
                'db_table': 'league_promotion_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='leaguegroup',
            constraint=models.UniqueConstraint(fields=('season', 'order'), name='unique_league_group_order'),
        ),
    ]
