# Generated by Django 5.0.6 on 2026-08-11 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_auditlog_changes'),
        ('exams', '0005_add_mathtopic_subject_name_unique'),
        ('students', '0003_stream_studentprofile_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, help_text='Optional — defaults to "<Topic> Quiz" or the date.', max_length=200)),
                ('term', models.CharField(choices=[('term_1', 'Term I (Jan–Apr)'), ('term_2', 'Term II (May–Aug)'), ('term_3', 'Term III (Sep–Dec)'), ('annual', 'Annual')], max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_score', models.DecimalField(decimal_places=2, default=5, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quizzes', to='students.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_quizzes', to='accounts.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_quizzes', to='exams.mathtopic')),
            ],
            options={
                'db_table': 'daily_quizzes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_quiz_scores', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quizzes.dailyquiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to='students.studentprofile')),
            ],
            options={
                'db_table': 'daily_quiz_scores',
                'ordering': ['-quiz__date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyquiz',
            constraint=models.CheckConstraint(check=models.Q(('max_score__gt', 0)), name='dailyquiz_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='dailyquizscore',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0)), name='dailyquizscore_score_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquizscore',
            unique_together={('quiz', 'student')},
        ),
    ]
