# Generated by Django 5.0.6 on 2026-08-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0005_add_mathtopic_subject_name_unique'),
        ('students', '0003_stream_studentprofile_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='award', help_text='lucide-react icon name', max_length=50)),
                ('criteria_type', models.CharField(max_length=30)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gamification_badges',
                'ordering': ['threshold', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_exam_date', models.DateField(blank=True, null=True)),
                ('last_result_passed', models.BooleanField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='students.studentprofile')),
            ],
            options={
                'db_table': 'gamification_student_streaks',
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.badge')),
                ('exam', models.ForeignKey(blank=True, help_text='The exam whose score triggered this award, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='students.studentprofile')),
            ],
            options={
                'db_table': 'gamification_student_badges',
                'ordering': ['-awarded_at'],
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
