# Generated by Django 5.0.6 on 2026-08-11 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_quizstreak'),
        ('quizzes', '0001_initial'),
        ('students', '0003_stream_studentprofile_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbadge',
            name='quiz',
            field=models.ForeignKey(blank=True, help_text='The daily quiz whose score triggered this award, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.dailyquiz'),
        ),
        migrations.AddField(
            model_name='quizstreak',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_streak', to='students.studentprofile'),
        ),
    ]
