# Generated by Django 5.0.6 on 2026-08-16 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0005_add_mathtopic_subject_name_unique'),
        ('students', '0004_studentprofile_target_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('codename', models.CharField(blank=True, help_text='Optional operation codename shown on the dossier header, e.g. "OPERATION HISABATI"', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('individual', 'Student vs Student'), ('stream', 'Stream vs Stream')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('live', 'Live — Awaiting Exam Results'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(help_text='Countdown target while registration is open — students must register before this.')),
                ('max_entrants', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Students may self-register when true')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='students.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(help_text='The exam whose scores decide this tournament.', on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='exams.exam')),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-registration_deadline'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_average', models.FloatField(blank=True, help_text="Entrant's prior average % at registration time", null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_tournament_entries', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='students.stream')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='students.studentprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_entries',
                'ordering': ['-seed_average'],
            },
        ),
        migrations.CreateModel(
            name='EntryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percentage', models.FloatField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('prior_average', models.FloatField(blank=True, help_text="Entrant's historical average % before this exam", null=True)),
                ('delta', models.FloatField(blank=True, help_text='score_percentage minus prior_average', null=True)),
                ('is_rising_star', models.BooleanField(default=False, help_text='Improved sharply vs their own prior average')),
                ('is_champion', models.BooleanField(default=False, help_text='Ranked #1 overall in this tournament')),
                ('is_absent', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tournaments.tournamententry')),
            ],
            options={
                'db_table': 'tournament_entry_results',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. "Duel — Front Row Showdown"', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Results'), ('resolved', 'Resolved'), ('void', 'Void')], default='pending', max_length=15)),
                ('is_tie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_challenges', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='tournaments.tournament')),
                ('entries', models.ManyToManyField(related_name='challenges', to='tournaments.tournamententry')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_challenges', to='tournaments.tournamententry')),
            ],
            options={
                'db_table': 'tournament_challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamententry',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('tournament', 'student'), name='unique_tournament_student_entry'),
        ),
        migrations.AddConstraint(
            model_name='tournamententry',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', False)), fields=('tournament', 'stream'), name='unique_tournament_stream_entry'),
        ),
    ]
