# Generated by Django 5.0.6 on 2026-07-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sitesettings_legal_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pwa_icon_url',
            field=models.URLField(blank=True, default='', help_text='URL to a square image (512×512 recommended) used as the installed app / home-screen icon'),
            preserve_default=False,
        ),
    ]
