# Generated by Django 5.0.6 on 2026-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_teacherassignment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
