# Generated by Django 5.2.17 on 2026-08-24 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_auditlog_changes'),
        ('students', '0004_studentprofile_target_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=15)),
                ('trigger_reason', models.CharField(blank=True, help_text='Why this student was flagged, e.g. "No improvement across the last 6 exams".', max_length=255)),
                ('baseline_average', models.FloatField(help_text="Student's historical average %% at program start.")),
                ('latest_average', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_programs', to='students.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_programs', to='students.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_programs', to='accounts.subject')),
            ],
            options={
                'db_table': 'intervention_programs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Locked'), ('active', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('measured_before', models.FloatField(blank=True, help_text="Student's average %% right before this stage started.", null=True)),
                ('measured_after', models.FloatField(blank=True, help_text="Student's average %% when this stage was marked complete.", null=True)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='interventions.interventionprogram')),
            ],
            options={
                'db_table': 'intervention_stages',
                'ordering': ['program', 'order'],
                'unique_together': {('program', 'order')},
            },
        ),
    ]
