# Generated by Django 5.0.6 on 2026-07-26 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0002_alter_studentprofile_index_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('avoid', 'Keep Apart'), ('prefer', 'Keep Together')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_constraints', to='students.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_peer_constraints', to=settings.AUTH_USER_MODEL)),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_constraints_as_a', to='students.studentprofile')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_constraints_as_b', to='students.studentprofile')),
            ],
            options={
                'db_table': 'peer_constraints',
                'ordering': ['-created_at'],
                'unique_together': {('classroom', 'student_a', 'student_b', 'constraint_type')},
            },
        ),
    ]
