# Generated by Django 5.2.8 on 2026-07-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_peerconstraint'),
        ('students', '0003_stream_studentprofile_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='stream',
            field=models.ForeignKey(
                blank=True, null=True,
                help_text='Optional — restrict this group to students in one stream within the classroom '
                           '(e.g. Form 2 "A"). Must belong to the same classroom as the group.',
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='student_groups', to='students.stream',
            ),
        ),
    ]
