# Generated by Django 5.2.17 on 2026-08-19 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auditlog_changes'),
        ('groups', '0003_studentgroup_stream'),
        ('students', '0004_studentprofile_target_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('classwork', 'Classwork'), ('homework', 'Homework'), ('project', 'Project'), ('practical', 'Practical'), ('presentation', 'Presentation'), ('other', 'Other')], default='classwork', max_length=20)),
                ('term', models.CharField(blank=True, choices=[('term_1', 'Term I (Jan–Apr)'), ('term_2', 'Term II (May–Aug)'), ('term_3', 'Term III (Sep–Dec)'), ('annual', 'Annual')], max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('date_given', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='students.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_assignments', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, help_text='Optional — restrict this assignment to groups in one stream.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_assignments', to='students.stream')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_assignments', to='accounts.subject')),
            ],
            options={
                'db_table': 'group_assignments',
                'ordering': ['-date_given', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupAssignmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_absent', models.BooleanField(default=False, help_text='Whole group did not submit / present.')),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_scores', to='groups.groupassignment')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_group_assignment_scores', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_scores', to='groups.studentgroup')),
            ],
            options={
                'db_table': 'group_assignment_scores',
                'ordering': ['-assignment__date_given', 'group__name'],
                'unique_together': {('assignment', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupAssignmentMemberMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Added to (or, if negative, subtracted from) the group score for this student only.', max_digits=6)),
                ('is_excused', models.BooleanField(default=False, help_text="Excluded from this student's and the group's analytics (e.g. was absent for this piece of work).")),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignment_marks', to='students.studentprofile')),
                ('group_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_marks', to='groups.groupassignmentscore')),
            ],
            options={
                'db_table': 'group_assignment_member_marks',
                'ordering': ['student__user__first_name'],
                'unique_together': {('group_score', 'student')},
            },
        ),
    ]
