"""
PDF/Excel export engine for peer-learning groups.

Kept separate from mathapi.apps.reports (which handles exam/classroom
report cards) since groups exports have their own fixed footer and a
different document shape (badges, tier breakdowns, roster sections)
that doesn't belong mixed into the general report engine.
"""
import io
import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage, KeepTogether,
)
from reportlab.graphics.shapes import Drawing, Circle

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.drawing.image import Image as XLImage

# ── Shared branding ──────────────────────────────────────────────────────────
BRAND_BLUE  = colors.HexColor('#2563eb')
BRAND_DARK  = colors.HexColor('#0a0a0f')
BRAND_GRAY  = colors.HexColor('#6b7280')
BRAND_LIGHT = colors.HexColor('#f3f4f6')
BRAND_GREEN = colors.HexColor('#10b981')
BRAND_AMBER = colors.HexColor('#f59e0b')
BRAND_ROSE  = colors.HexColor('#f43f5e')
WHITE = colors.white

PAGE_W, PAGE_H = A4
MARGIN = 1.8 * cm

# The specific footer text requested for every group export — distinct from
# the "Generated by MathPlatform" footer used on the general reports app.
FOOTER_TEXT = 'Trust Thyself - DarkSeid'

TIER_LABELS = {
    'very_strong': 'Very Strong', 'strong': 'Strong',
    'average': 'Average', 'weak': 'Weak', 'unrated': 'Not Yet Rated',
}
TIER_COLORS_PDF = {
    'very_strong': BRAND_GREEN, 'strong': BRAND_BLUE,
    'average': BRAND_AMBER, 'weak': BRAND_ROSE, 'unrated': BRAND_GRAY,
}
TIER_COLORS_XL = {
    'very_strong': 'FF10b981', 'strong': 'FF2563eb',
    'average': 'FFf59e0b', 'weak': 'FFf43f5e', 'unrated': 'FF9ca3af',
}


def _badge_path(group):
    if not group.badge_image:
        return None
    try:
        path = group.badge_image.path
        return path if os.path.exists(path) else None
    except (ValueError, OSError):
        return None


def _meta_lines(classroom, extra: dict) -> list[str]:
    lines = [
        f'Class: {classroom}',
        f'Grade Level: {classroom.grade_level.name}',
        f'Academic Year: {extra.get("academic_year") or classroom.academic_year}',
    ]
    if extra.get('subject_name'):
        lines.append(f'Subject: {extra["subject_name"]}')
    if extra.get('term_display'):
        lines.append(f'Term: {extra["term_display"]}')
    lines.append(f'Generated: {datetime.now().strftime("%d %B %Y, %H:%M")}')
    if extra.get('generated_by'):
        lines.append(f'Generated by: {extra["generated_by"]}')
    return lines


# ═════════════════════════════════ PDF ══════════════════════════════════════

def _pdf_styles():
    base = getSampleStyleSheet()
    styles = {}
    styles['title'] = ParagraphStyle('title', fontSize=18, fontName='Helvetica-Bold',
                                      textColor=BRAND_DARK, spaceAfter=2, alignment=TA_LEFT)
    styles['subtitle'] = ParagraphStyle('subtitle', fontSize=9.5, fontName='Helvetica',
                                         textColor=BRAND_GRAY, spaceAfter=2, alignment=TA_LEFT, leading=13)
    styles['section'] = ParagraphStyle('section', fontSize=12, fontName='Helvetica-Bold',
                                        textColor=WHITE, spaceBefore=0, spaceAfter=0)
    styles['body'] = ParagraphStyle('body', fontSize=8.5, fontName='Helvetica', textColor=BRAND_DARK)
    styles['footer'] = ParagraphStyle('footer', fontSize=8, fontName='Helvetica-Bold',
                                       textColor=BRAND_GRAY, alignment=TA_CENTER)
    return base, styles


def _header_footer(canvas, doc, meta):
    canvas.saveState()
    canvas.setFillColor(BRAND_BLUE)
    canvas.rect(MARGIN, PAGE_H - 2.1*cm, PAGE_W - 2*MARGIN, 1.3*cm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont('Helvetica-Bold', 13)
    canvas.drawString(MARGIN + 0.3*cm, PAGE_H - 1.4*cm, meta['school_name'])
    canvas.setFont('Helvetica', 9)
    canvas.drawRightString(PAGE_W - MARGIN - 0.3*cm, PAGE_H - 1.4*cm, meta['doc_title'])

    canvas.setFillColor(BRAND_DARK)
    y = PAGE_H - 2.7*cm
    canvas.setFont('Helvetica', 8)
    for line in meta['meta_lines']:
        canvas.drawString(MARGIN, y, line)
        y -= 0.32*cm

    canvas.setStrokeColor(BRAND_LIGHT)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 1.5*cm, PAGE_W - MARGIN, 1.5*cm)
    canvas.setFillColor(BRAND_GRAY)
    canvas.setFont('Helvetica-Bold', 8)
    canvas.drawCentredString(PAGE_W / 2, 1.1*cm, FOOTER_TEXT)
    canvas.setFont('Helvetica', 7)
    canvas.drawRightString(PAGE_W - MARGIN, 1.1*cm, f'Page {doc.page}')
    canvas.restoreState()


def _tier_row_bg(tier):
    return colors.HexColor('#ecfdf5') if tier == 'very_strong' else \
           colors.HexColor('#eff6ff') if tier == 'strong' else \
           colors.HexColor('#fffbeb') if tier == 'average' else \
           colors.HexColor('#fef2f2') if tier == 'weak' else colors.HexColor('#f9fafb')


def generate_groups_summary_pdf(classroom, groups: list, extra: dict) -> bytes:
    """One row per group: name, size, tier breakdown, group average."""
    buf = io.BytesIO()
    top_margin = 3.3*cm + 0.32*cm*len(extra['meta_lines'])
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=top_margin, bottomMargin=2.0*cm,
                             leftMargin=MARGIN, rightMargin=MARGIN)
    _, styles = _pdf_styles()
    story = [Spacer(1, 0.2*cm)]

    header = ['Group', 'Members', 'Very Strong', 'Strong', 'Average', 'Weak', 'Group Avg %']
    rows = [header]
    for g in groups:
        counts = {'very_strong': 0, 'strong': 0, 'average': 0, 'weak': 0}
        avgs = []
        for m in g.memberships.all():
            if m.tier in counts:
                counts[m.tier] += 1
            if m.average_at_placement is not None:
                avgs.append(m.average_at_placement)
        group_avg = round(sum(avgs) / len(avgs), 1) if avgs else '—'
        rows.append([
            g.name, str(g.memberships.count()),
            str(counts['very_strong']), str(counts['strong']),
            str(counts['average']), str(counts['weak']),
            f'{group_avg}%' if group_avg != '—' else '—',
        ])

    t = Table(rows, colWidths=[5.2*cm, 2.2*cm, 2.6*cm, 2.2*cm, 2.2*cm, 2.0*cm, 2.6*cm], repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), BRAND_DARK),
        ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, BRAND_LIGHT]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t)

    meta = {
        'school_name': extra['school_name'], 'doc_title': 'Group Summary',
        'meta_lines': extra['meta_lines'],
    }
    doc.build(story, onFirstPage=lambda c, d: _header_footer(c, d, meta),
              onLaterPages=lambda c, d: _header_footer(c, d, meta))
    return buf.getvalue()


def generate_groups_roster_pdf(classroom, groups: list, extra: dict) -> bytes:
    """One section per group: badge + name header, then a member table
    with each student's tier and score."""
    buf = io.BytesIO()
    top_margin = 3.3*cm + 0.32*cm*len(extra['meta_lines'])
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=top_margin, bottomMargin=2.0*cm,
                             leftMargin=MARGIN, rightMargin=MARGIN)
    base, styles = _pdf_styles()
    story = [Spacer(1, 0.2*cm)]

    for g in groups:
        section = []
        # Badge + name banner
        badge_path = _badge_path(g)
        banner_cells = []
        if badge_path:
            try:
                img = RLImage(badge_path, width=1.2*cm, height=1.2*cm)
                banner_cells.append(img)
            except Exception:
                banner_cells.append('')
        else:
            d = Drawing(1.2*cm, 1.2*cm)
            d.add(Circle(0.6*cm, 0.6*cm, 0.55*cm, fillColor=colors.HexColor(g.badge_color), strokeColor=None))
            banner_cells.append(d)
        title = f'{g.name}' + (f'  ·  {g.subject.name}' if g.subject_id else '')
        banner_cells.append(Paragraph(title, styles['section']))
        banner = Table([banner_cells], colWidths=[1.6*cm, None])
        banner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), BRAND_DARK),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (0, 0), 8), ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        section.append(banner)

        members = sorted(g.memberships.all(), key=lambda m: -(m.average_at_placement or 0))
        rows = [['#', 'Student Name', 'Student ID', 'Tier', 'Score %']]
        row_bgs = [WHITE]
        for i, m in enumerate(members, start=1):
            rows.append([
                str(i), m.student.full_name, m.student.student_id,
                TIER_LABELS.get(m.tier, m.tier),
                f'{m.average_at_placement}%' if m.average_at_placement is not None else '—',
            ])
            row_bgs.append(_tier_row_bg(m.tier))
        if len(rows) == 1:
            rows.append(['—', 'No members yet', '', '', ''])
            row_bgs.append(WHITE)

        member_table = Table(rows, colWidths=[1.0*cm, 6.0*cm, 3.0*cm, 3.4*cm, 2.6*cm], repeatRows=1)
        style_cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 4), ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]
        for i, bg in enumerate(row_bgs):
            if i == 0:
                continue
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
        member_table.setStyle(TableStyle(style_cmds))
        section.append(member_table)
        section.append(Spacer(1, 0.5*cm))
        story.append(KeepTogether(section))

    meta = {
        'school_name': extra['school_name'], 'doc_title': 'Group Rosters & Scores',
        'meta_lines': extra['meta_lines'],
    }
    doc.build(story, onFirstPage=lambda c, d: _header_footer(c, d, meta),
              onLaterPages=lambda c, d: _header_footer(c, d, meta))
    return buf.getvalue()


# ═════════════════════════════════ Excel ═════════════════════════════════════

def _fill(hexcolor):
    return PatternFill('solid', fgColor=hexcolor)


def _thin_border():
    s = Side(style='thin', color='FFD1D5DB')
    return Border(left=s, right=s, top=s, bottom=s)


def _write_xl_header(ws, extra, doc_title, ncols):
    row = 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
    c = ws.cell(row, 1, extra['school_name'])
    c.font = Font(bold=True, color='FFFFFFFF', size=13)
    c.fill = _fill('FF1e3a5f')
    c.alignment = Alignment(horizontal='center')
    ws.row_dimensions[row].height = 22
    row += 1

    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
    c = ws.cell(row, 1, doc_title)
    c.font = Font(bold=True, color='FFFFFFFF', size=11)
    c.fill = _fill('FF2d4f7c')
    c.alignment = Alignment(horizontal='center')
    row += 1

    for line in extra['meta_lines']:
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
        c = ws.cell(row, 1, line)
        c.font = Font(italic=True, color='FF374151', size=9)
        c.fill = _fill('FFE8EFF9')
        c.alignment = Alignment(horizontal='center')
        row += 1
    return row + 1  # next free row


def _write_xl_footer(ws, row, ncols):
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
    c = ws.cell(row, 1, FOOTER_TEXT)
    c.font = Font(bold=True, italic=True, color='FF6b7280', size=9)
    c.alignment = Alignment(horizontal='center')
    # Also set as the printed page footer so it appears on every printed page.
    ws.oddFooter.center.text = FOOTER_TEXT
    ws.oddFooter.center.size = 9
    ws.evenFooter.center.text = FOOTER_TEXT


def generate_groups_summary_excel(classroom, groups: list, extra: dict) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = 'Group Summary'
    ncols = 7
    headers = ['Group', 'Members', 'Very Strong', 'Strong', 'Average', 'Weak', 'Group Avg %']
    row = _write_xl_header(ws, extra, 'Group Summary', ncols)

    for i, h in enumerate(headers, start=1):
        c = ws.cell(row, i, h)
        c.font = Font(bold=True, color='FFFFFFFF', size=10)
        c.fill = _fill('FF111827')
        c.alignment = Alignment(horizontal='center')
        c.border = _thin_border()
    row += 1

    for g in groups:
        counts = {'very_strong': 0, 'strong': 0, 'average': 0, 'weak': 0}
        avgs = []
        for m in g.memberships.all():
            if m.tier in counts:
                counts[m.tier] += 1
            if m.average_at_placement is not None:
                avgs.append(m.average_at_placement)
        group_avg = round(sum(avgs) / len(avgs), 1) if avgs else None
        values = [g.name, g.memberships.count(), counts['very_strong'], counts['strong'],
                  counts['average'], counts['weak'], f'{group_avg}%' if group_avg is not None else '—']
        for i, v in enumerate(values, start=1):
            c = ws.cell(row, i, v)
            c.border = _thin_border()
            c.alignment = Alignment(horizontal='center' if i > 1 else 'left')
        row += 1

    row += 1
    _write_xl_footer(ws, row, ncols)

    widths = [26, 12, 14, 12, 12, 10, 14]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_groups_roster_excel(classroom, groups: list, extra: dict) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = 'Group Rosters'
    ncols = 5
    row = _write_xl_header(ws, extra, 'Group Rosters & Scores', ncols)

    for g in groups:
        # Group banner row, with badge image if available.
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
        title = g.name + (f'  ·  {g.subject.name}' if g.subject_id else '')
        c = ws.cell(row, 1, title)
        c.font = Font(bold=True, color='FFFFFFFF', size=12)
        c.fill = _fill(g.badge_color.replace('#', 'FF') if g.badge_color else 'FF2563eb')
        c.alignment = Alignment(horizontal='left', indent=2)
        ws.row_dimensions[row].height = 24
        badge_path = _badge_path(g)
        if badge_path:
            try:
                img = XLImage(badge_path)
                img.height, img.width = 28, 28
                img.anchor = f'A{row}'
                ws.add_image(img)
            except Exception:
                pass
        row += 1

        headers = ['#', 'Student Name', 'Student ID', 'Tier', 'Score %']
        for i, h in enumerate(headers, start=1):
            c = ws.cell(row, i, h)
            c.font = Font(bold=True, size=9, color='FFFFFFFF')
            c.fill = _fill('FF374151')
            c.border = _thin_border()
            c.alignment = Alignment(horizontal='center')
        row += 1

        members = sorted(g.memberships.all(), key=lambda m: -(m.average_at_placement or 0))
        if not members:
            ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
            ws.cell(row, 1, 'No members yet').alignment = Alignment(horizontal='center')
            row += 1
        for i, m in enumerate(members, start=1):
            values = [i, m.student.full_name, m.student.student_id,
                      TIER_LABELS.get(m.tier, m.tier),
                      f'{m.average_at_placement}%' if m.average_at_placement is not None else '—']
            for col, v in enumerate(values, start=1):
                c = ws.cell(row, col, v)
                c.border = _thin_border()
                c.alignment = Alignment(horizontal='center' if col != 2 else 'left')
                if col == 4:
                    c.fill = _fill(TIER_COLORS_XL.get(m.tier, 'FFFFFFFF'))
                    c.font = Font(color='FFFFFFFF', bold=True, size=9)
            row += 1
        row += 1  # blank row between groups

    _write_xl_footer(ws, row, ncols)

    widths = [5, 26, 14, 16, 12]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
