"""
PDF/Excel export engine for peer-learning groups.

Kept separate from mathapi.apps.reports (which handles exam/classroom
report cards) since groups exports have their own fixed footer and a
different document shape (badges, tier breakdowns, roster sections)
that doesn't belong mixed into the general report engine.
"""
import io
import os
from datetime import datetime
from xml.sax.saxutils import escape as _xml_escape

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage, KeepTogether,
)
from reportlab.graphics.shapes import Drawing, Circle

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.drawing.image import Image as XLImage

# ── Shared branding ──────────────────────────────────────────────────────────
BRAND_BLUE  = colors.HexColor('#2563eb')
BRAND_DARK  = colors.HexColor('#0a0a0f')
BRAND_GRAY  = colors.HexColor('#6b7280')
BRAND_LIGHT = colors.HexColor('#f3f4f6')
BRAND_GREEN = colors.HexColor('#10b981')
BRAND_AMBER = colors.HexColor('#f59e0b')
BRAND_ROSE  = colors.HexColor('#f43f5e')
WHITE = colors.white

PAGE_W, PAGE_H = A4
MARGIN = 1.8 * cm

# The specific footer text requested for every group export — distinct from
# the "Generated by MathPlatform" footer used on the general reports app.
FOOTER_TEXT = 'Trust Thyself - DarkSeid'

TIER_LABELS = {
    'very_strong': 'Very Strong', 'strong': 'Strong',
    'average': 'Average', 'weak': 'Weak', 'unrated': 'Not Yet Rated',
}
TIER_COLORS_PDF = {
    'very_strong': BRAND_GREEN, 'strong': BRAND_BLUE,
    'average': BRAND_AMBER, 'weak': BRAND_ROSE, 'unrated': BRAND_GRAY,
}
TIER_COLORS_XL = {
    'very_strong': 'FF10b981', 'strong': 'FF2563eb',
    'average': 'FFf59e0b', 'weak': 'FFf43f5e', 'unrated': 'FF9ca3af',
}


def _esc(v) -> str:
    """Escape a value before it's interpolated into ReportLab's mini-XML
    Paragraph markup. Any teacher-entered text (group names, badge
    labels, etc.) can contain '<', '>', or '&' — ordinary in a maths
    platform ("x < y", "Form 3 & 4") — and an unescaped one throws a
    ReportLab ParseError that 500s the whole export."""
    return _xml_escape(str(v))


def _badge_path(group):
    if not group.badge_image:
        return None
    try:
        path = group.badge_image.path
        return path if os.path.exists(path) else None
    except (ValueError, OSError):
        return None


def _meta_lines(classroom, extra: dict) -> list[str]:
    lines = [
        f'Class: {classroom}',
        f'Grade Level: {classroom.grade_level.name}',
        f'Academic Year: {extra.get("academic_year") or classroom.academic_year}',
    ]
    if extra.get('subject_name'):
        lines.append(f'Subject: {extra["subject_name"]}')
    if extra.get('term_display'):
        lines.append(f'Term: {extra["term_display"]}')
    lines.append(f'Generated: {datetime.now().strftime("%d %B %Y, %H:%M")}')
    if extra.get('generated_by'):
        lines.append(f'Generated by: {extra["generated_by"]}')
    return lines


# ═════════════════════════════════ PDF ══════════════════════════════════════

def _pdf_styles():
    base = getSampleStyleSheet()
    styles = {}
    styles['title'] = ParagraphStyle('title', fontSize=18, fontName='Helvetica-Bold',
                                      textColor=BRAND_DARK, spaceAfter=2, alignment=TA_LEFT)
    styles['subtitle'] = ParagraphStyle('subtitle', fontSize=9.5, fontName='Helvetica',
                                         textColor=BRAND_GRAY, spaceAfter=2, alignment=TA_LEFT, leading=13)
    styles['section'] = ParagraphStyle('section', fontSize=12, fontName='Helvetica-Bold',
                                        textColor=WHITE, spaceBefore=0, spaceAfter=0)
    styles['body'] = ParagraphStyle('body', fontSize=8.5, fontName='Helvetica', textColor=BRAND_DARK)
    styles['footer'] = ParagraphStyle('footer', fontSize=8, fontName='Helvetica-Bold',
                                       textColor=BRAND_GRAY, alignment=TA_CENTER)
    # Small caps label + bold value, used by the meta-info card grid below
    # the header — matches the styling reports/pdf_engine.py already uses
    # for its summary-stat cards, so group exports look consistent with
    # the rest of the app's PDFs instead of being a plain text list.
    styles['meta_label'] = ParagraphStyle('meta_label', fontSize=7, fontName='Helvetica-Bold',
                                           textColor=BRAND_GRAY, spaceAfter=1)
    styles['meta_value'] = ParagraphStyle('meta_value', fontSize=8.5, fontName='Helvetica-Bold',
                                           textColor=BRAND_DARK, leading=10)
    return base, styles


def _meta_pairs(classroom, extra: dict) -> list[tuple[str, str]]:
    """Structured (LABEL, value) pairs for the meta-info card grid — the
    same data _meta_lines used to flatten into plain text lines."""
    pairs = [
        ('CLASS', str(classroom)),
        ('GRADE LEVEL', classroom.grade_level.name),
        ('ACADEMIC YEAR', extra.get('academic_year') or classroom.academic_year),
    ]
    if extra.get('subject_name'):
        pairs.append(('SUBJECT', extra['subject_name']))
    if extra.get('term_display'):
        pairs.append(('TERM', extra['term_display']))
    pairs.append(('GENERATED', datetime.now().strftime('%d %b %y, %H:%M')))
    if extra.get('generated_by'):
        pairs.append(('GENERATED BY', extra['generated_by']))
    return pairs


def _meta_grid(meta_items: list[tuple[str, str]], styles) -> Table:
    """Render the Class / Grade Level / Subject / etc. block as a row of
    bordered, labelled cards instead of a stack of plain text lines."""
    label_row = [Paragraph(_esc(label), styles['meta_label']) for label, _ in meta_items]
    value_row = [Paragraph(_esc(val), styles['meta_value']) for _, val in meta_items]
    col_w = (PAGE_W - 2*MARGIN) / len(meta_items)
    t = Table([label_row, value_row], colWidths=[col_w] * len(meta_items))
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), BRAND_LIGHT),
        ('BACKGROUND', (0, 1), (-1, 1), WHITE),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
        ('INNERGRID', (0, 0), (-1, -1), 0.3, colors.HexColor('#e5e7eb')),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    return t


def _header_footer(canvas, doc, meta):
    canvas.saveState()
    canvas.setFillColor(BRAND_BLUE)
    canvas.rect(MARGIN, PAGE_H - 2.1*cm, PAGE_W - 2*MARGIN, 1.3*cm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont('Helvetica-Bold', 13)
    canvas.drawString(MARGIN + 0.3*cm, PAGE_H - 1.4*cm, meta['school_name'])
    canvas.setFont('Helvetica', 9)
    canvas.drawRightString(PAGE_W - MARGIN - 0.3*cm, PAGE_H - 1.4*cm, meta['doc_title'])

    canvas.setStrokeColor(BRAND_LIGHT)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 1.5*cm, PAGE_W - MARGIN, 1.5*cm)
    canvas.setFillColor(BRAND_GRAY)
    canvas.setFont('Helvetica-Bold', 8)
    canvas.drawCentredString(PAGE_W / 2, 1.1*cm, FOOTER_TEXT)
    canvas.setFont('Helvetica', 7)
    canvas.drawRightString(PAGE_W - MARGIN, 1.1*cm, f'Page {doc.page}')
    canvas.restoreState()


def _tier_row_bg(tier):
    return colors.HexColor('#ecfdf5') if tier == 'very_strong' else \
           colors.HexColor('#eff6ff') if tier == 'strong' else \
           colors.HexColor('#fffbeb') if tier == 'average' else \
           colors.HexColor('#fef2f2') if tier == 'weak' else colors.HexColor('#f9fafb')


def generate_groups_summary_pdf(classroom, groups: list, extra: dict) -> bytes:
    """One row per group: name, size, tier breakdown, group average."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2.9*cm, bottomMargin=2.0*cm,
                             leftMargin=MARGIN, rightMargin=MARGIN)
    _, styles = _pdf_styles()
    story = [
        _meta_grid(_meta_pairs(classroom, extra), styles),
        Spacer(1, 0.5*cm),
    ]

    header = ['Group', 'Members', 'Very Strong', 'Strong', 'Average', 'Weak', 'Group Avg %']
    rows = [header]
    group_avgs = []  # for the group-avg cell colour, and a left colour swatch per row
    for g in groups:
        counts = {'very_strong': 0, 'strong': 0, 'average': 0, 'weak': 0}
        avgs = []
        for m in g.memberships.all():
            if m.tier in counts:
                counts[m.tier] += 1
            if m.average_at_placement is not None:
                avgs.append(m.average_at_placement)
        group_avg = round(sum(avgs) / len(avgs), 1) if avgs else None
        group_avgs.append(group_avg)
        rows.append([
            Paragraph(f'<font color="{g.badge_color}">●</font> {_esc(g.name)}', styles['body']),
            str(g.memberships.count()),
            str(counts['very_strong']), str(counts['strong']),
            str(counts['average']), str(counts['weak']),
            f'{group_avg}%' if group_avg is not None else '—',
        ])

    def _avg_color(pct):
        if pct is None:
            return BRAND_GRAY
        if pct >= 65: return BRAND_GREEN
        if pct >= 45: return BRAND_AMBER
        return BRAND_ROSE

    t = Table(rows, colWidths=[5.2*cm, 2.2*cm, 2.6*cm, 2.2*cm, 2.2*cm, 2.0*cm, 2.6*cm], repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), BRAND_DARK),
        ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, BRAND_LIGHT]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        # Tier-count columns tinted the same colours used everywhere else
        # in the app (very strong = green, strong = blue, average = amber,
        # weak = rose) so the summary table reads at a glance, not just
        # as a grid of plain numbers.
        ('TEXTCOLOR', (2, 1), (2, -1), TIER_COLORS_PDF['very_strong']),
        ('TEXTCOLOR', (3, 1), (3, -1), TIER_COLORS_PDF['strong']),
        ('TEXTCOLOR', (4, 1), (4, -1), TIER_COLORS_PDF['average']),
        ('TEXTCOLOR', (5, 1), (5, -1), TIER_COLORS_PDF['weak']),
        ('FONTNAME', (2, 1), (5, -1), 'Helvetica-Bold'),
    ]
    for i, avg in enumerate(group_avgs, start=1):
        style_cmds.append(('TEXTCOLOR', (6, i), (6, i), _avg_color(avg)))
        style_cmds.append(('FONTNAME', (6, i), (6, i), 'Helvetica-Bold'))
    t.setStyle(TableStyle(style_cmds))
    story.append(t)

    meta = {'school_name': extra['school_name'], 'doc_title': 'Group Summary'}
    doc.build(story, onFirstPage=lambda c, d: _header_footer(c, d, meta),
              onLaterPages=lambda c, d: _header_footer(c, d, meta))
    return buf.getvalue()


def generate_groups_roster_pdf(classroom, groups: list, extra: dict) -> bytes:
    """One section per group: badge + name header, then a member table
    with each student's tier and score."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2.9*cm, bottomMargin=2.0*cm,
                             leftMargin=MARGIN, rightMargin=MARGIN)
    base, styles = _pdf_styles()
    story = [
        _meta_grid(_meta_pairs(classroom, extra), styles),
        Spacer(1, 0.5*cm),
    ]


    for g in groups:
        section = []
        # Badge + name banner
        badge_path = _badge_path(g)
        banner_cells = []
        if badge_path:
            try:
                img = RLImage(badge_path, width=1.2*cm, height=1.2*cm)
                banner_cells.append(img)
            except Exception:
                banner_cells.append('')
        else:
            d = Drawing(1.2*cm, 1.2*cm)
            d.add(Circle(0.6*cm, 0.6*cm, 0.55*cm, fillColor=colors.HexColor(g.badge_color), strokeColor=None))
            banner_cells.append(d)
        title = f'{_esc(g.name)}' + (f'  \u00b7  {_esc(g.subject.name)}' if g.subject_id else '')
        banner_cells.append(Paragraph(title, styles['section']))
        banner = Table([banner_cells], colWidths=[1.6*cm, None])
        # Each group's banner is tinted with its own badge colour instead of
        # a flat dark bar — makes it easy to visually jump between groups
        # in a long multi-group roster, and mirrors the coloured card
        # banners in the app itself.
        banner_bg = colors.HexColor(g.badge_color) if g.badge_color else BRAND_DARK
        banner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), banner_bg),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (0, 0), 8), ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        section.append(banner)

        members = sorted(g.memberships.all(), key=lambda m: -(m.average_at_placement or 0))
        rows = [['#', 'Student Name', 'Student ID', 'Tier', 'Score %']]
        row_bgs = [WHITE]
        row_tiers = [None]
        for i, m in enumerate(members, start=1):
            rows.append([
                str(i), m.student.full_name, m.student.student_id,
                TIER_LABELS.get(m.tier, m.tier),
                f'{m.average_at_placement}%' if m.average_at_placement is not None else '—',
            ])
            row_bgs.append(_tier_row_bg(m.tier))
            row_tiers.append(m.tier)
        if len(rows) == 1:
            rows.append(['—', 'No members yet', '', '', ''])
            row_bgs.append(WHITE)
            row_tiers.append(None)

        member_table = Table(rows, colWidths=[1.0*cm, 6.0*cm, 3.0*cm, 3.4*cm, 2.6*cm], repeatRows=1)
        style_cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 4), ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]
        for i, bg in enumerate(row_bgs):
            if i == 0:
                continue
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
            tier = row_tiers[i]
            if tier in TIER_COLORS_PDF:
                # Bold, tier-coloured text in the Tier column (not just a
                # pale row tint) so the ranking is legible even printed
                # in black & white grayscale.
                style_cmds.append(('TEXTCOLOR', (3, i), (3, i), TIER_COLORS_PDF[tier]))
                style_cmds.append(('FONTNAME', (3, i), (3, i), 'Helvetica-Bold'))
        member_table.setStyle(TableStyle(style_cmds))
        section.append(member_table)
        section.append(Spacer(1, 0.5*cm))
        story.append(KeepTogether(section))

    meta = {'school_name': extra['school_name'], 'doc_title': 'Group Rosters & Scores'}
    doc.build(story, onFirstPage=lambda c, d: _header_footer(c, d, meta),
              onLaterPages=lambda c, d: _header_footer(c, d, meta))
    return buf.getvalue()


def generate_group_work_analytics_pdf(classroom, analytics: dict, extra: dict) -> bytes:
    """
    Group Work Analytics summary: classroom headline, per-stream rollup,
    per-group rollup (sorted strongest-first), and the assignment-by-
    assignment trend — the PDF counterpart of the analytics page.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2.9*cm, bottomMargin=2.0*cm,
                             leftMargin=MARGIN, rightMargin=MARGIN)
    base, styles = _pdf_styles()
    story = [
        _meta_grid(_meta_pairs(classroom, extra), styles),
        Spacer(1, 0.4*cm),
    ]

    def _pct_color(pct):
        if pct is None:
            return BRAND_GRAY
        if pct >= 65: return BRAND_GREEN
        if pct >= 45: return BRAND_AMBER
        return BRAND_ROSE

    # Headline stat strip
    avg = analytics.get('classroom_average_pct')
    avg_value_style = ParagraphStyle('avg_value', parent=styles['meta_value'], textColor=_pct_color(avg))
    headline = Table([[
        Paragraph('CLASSROOM AVERAGE', styles['meta_label']),
        Paragraph('ASSIGNMENTS', styles['meta_label']),
        Paragraph('GROUPS SCORED', styles['meta_label']),
    ], [
        Paragraph(f'{avg}%' if avg is not None else '—', avg_value_style),
        Paragraph(str(analytics.get('assignments_count', 0)), styles['meta_value']),
        Paragraph(str(analytics.get('groups_scored_count', 0)), styles['meta_value']),
    ]], colWidths=[(PAGE_W - 2*MARGIN) / 3] * 3)
    headline.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), BRAND_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
        ('INNERGRID', (0, 0), (-1, -1), 0.3, colors.HexColor('#e5e7eb')),
        ('TOPPADDING', (0, 0), (-1, -1), 5), ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(headline)
    story.append(Spacer(1, 0.5*cm))

    # Per-stream rollup
    if analytics.get('per_stream'):
        story.append(Paragraph('By Stream', ParagraphStyle('h2', fontSize=11, fontName='Helvetica-Bold',
                                                             textColor=BRAND_DARK, spaceAfter=6)))
        rows = [['Stream', 'Groups', 'Assignments Scored', 'Average %']]
        for s in analytics['per_stream']:
            rows.append([s['stream_name'], str(s['group_count']), str(s['assignments_scored']), f"{s['average_pct']}%"])
        t = Table(rows, colWidths=[6.5*cm, 3*cm, 4.5*cm, 3*cm], repeatRows=1)
        style_cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), BRAND_DARK), ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'), ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, BRAND_LIGHT]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'), ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 5), ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]
        for i, s in enumerate(analytics['per_stream'], start=1):
            style_cmds.append(('TEXTCOLOR', (3, i), (3, i), _pct_color(s['average_pct'])))
            style_cmds.append(('FONTNAME', (3, i), (3, i), 'Helvetica-Bold'))
        t.setStyle(TableStyle(style_cmds))
        story.append(t)
        story.append(Spacer(1, 0.5*cm))

    # Per-group rollup
    story.append(Paragraph('By Group', ParagraphStyle('h2', fontSize=11, fontName='Helvetica-Bold',
                                                        textColor=BRAND_DARK, spaceAfter=6)))
    rows = [['Group', 'Stream', 'Assignments', 'Best %', 'Worst %', 'Average %']]
    for g in analytics.get('per_group', []):
        rows.append([
            g['group_name'], g['stream_name'] or '—', str(g['assignments_count']),
            f"{g['best_pct']}%", f"{g['worst_pct']}%", f"{g['average_pct']}%",
        ])
    t = Table(rows, colWidths=[4.6*cm, 3.4*cm, 2.6*cm, 2.4*cm, 2.4*cm, 2.6*cm], repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), BRAND_DARK), ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'), ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, BRAND_LIGHT]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
        ('ALIGN', (1, 0), (-1, -1), 'CENTER'), ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5), ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i, g in enumerate(analytics.get('per_group', []), start=1):
        style_cmds.append(('TEXTCOLOR', (5, i), (5, i), _pct_color(g['average_pct'])))
        style_cmds.append(('FONTNAME', (5, i), (5, i), 'Helvetica-Bold'))
    t.setStyle(TableStyle(style_cmds))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))

    # Assignment-by-assignment trend
    if analytics.get('trend'):
        story.append(Paragraph('Assignment Trend', ParagraphStyle('h2', fontSize=11, fontName='Helvetica-Bold',
                                                                    textColor=BRAND_DARK, spaceAfter=6)))
        rows = [['Date', 'Assignment', 'Groups Scored', 'Average %']]
        for t_row in analytics['trend']:
            rows.append([t_row['date'], t_row['title'], str(t_row['groups_scored']), f"{t_row['average_pct']}%"])
        t = Table(rows, colWidths=[2.6*cm, 7.4*cm, 3.2*cm, 2.8*cm], repeatRows=1)
        style_cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), BRAND_DARK), ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'), ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, BRAND_LIGHT]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
            ('ALIGN', (2, 0), (-1, -1), 'CENTER'), ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 5), ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]
        t.setStyle(TableStyle(style_cmds))
        story.append(t)

    meta = {'school_name': extra['school_name'], 'doc_title': 'Group Work Analytics'}
    doc.build(story, onFirstPage=lambda c, d: _header_footer(c, d, meta),
              onLaterPages=lambda c, d: _header_footer(c, d, meta))
    return buf.getvalue()


# ═════════════════════════════════ Excel ═════════════════════════════════════

def _fill(hexcolor):
    return PatternFill('solid', fgColor=hexcolor)


def _thin_border():
    s = Side(style='thin', color='FFD1D5DB')
    return Border(left=s, right=s, top=s, bottom=s)


def _write_xl_header(ws, classroom, extra, doc_title, ncols):
    row = 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
    c = ws.cell(row, 1, extra['school_name'])
    c.font = Font(bold=True, color='FFFFFFFF', size=13)
    c.fill = _fill('FF1e3a5f')
    c.alignment = Alignment(horizontal='center')
    ws.row_dimensions[row].height = 22
    row += 1

    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
    c = ws.cell(row, 1, doc_title)
    c.font = Font(bold=True, color='FFFFFFFF', size=11)
    c.fill = _fill('FF2d4f7c')
    c.alignment = Alignment(horizontal='center')
    row += 1

    # Each meta field (Class / Grade Level / Subject / Term / Generated…)
    # gets its own labelled "card" row — a coloured label chip on the
    # left, its value on the right — instead of one plain italic
    # sentence per field. Colour keyed by field type so it visually
    # matches the same palette used across the app (blue = class info,
    # violet = grade level, green = subject, amber = term).
    FIELD_COLORS = {
        'CLASS':          ('FFDCEAFE', 'FF1D4ED8'),
        'GRADE LEVEL':     ('FFEDE9FE', 'FF6D28D9'),
        'ACADEMIC YEAR':   ('FFF3F4F6', 'FF374151'),
        'SUBJECT':         ('FFD1FAE5', 'FF047857'),
        'TERM':            ('FFFEF3C7', 'FFB45309'),
        'GENERATED':       ('FFF3F4F6', 'FF6B7280'),
        'GENERATED BY':    ('FFF3F4F6', 'FF6B7280'),
    }
    label_span = max(1, ncols // 3)
    for label, value in _meta_pairs(classroom, extra):
        bg, fg = FIELD_COLORS.get(label, ('FFF3F4F6', 'FF374151'))
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=label_span)
        lc = ws.cell(row, 1, label)
        lc.font = Font(bold=True, color=fg, size=8)
        lc.fill = _fill(bg)
        lc.alignment = Alignment(horizontal='left', indent=1, vertical='center')
        ws.merge_cells(start_row=row, start_column=label_span + 1, end_row=row, end_column=ncols)
        vc = ws.cell(row, label_span + 1, value)
        vc.font = Font(bold=True, color='FF111827', size=9.5)
        vc.fill = _fill('FFFFFFFF')
        vc.alignment = Alignment(horizontal='left', indent=1, vertical='center')
        for col in range(1, ncols + 1):
            ws.cell(row, col).border = _thin_border()
        ws.row_dimensions[row].height = 18
        row += 1
    return row + 1  # next free row


def _write_xl_footer(ws, row, ncols):
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
    c = ws.cell(row, 1, FOOTER_TEXT)
    c.font = Font(bold=True, italic=True, color='FF6b7280', size=9)
    c.alignment = Alignment(horizontal='center')
    # Also set as the printed page footer so it appears on every printed page.
    ws.oddFooter.center.text = FOOTER_TEXT
    ws.oddFooter.center.size = 9
    ws.evenFooter.center.text = FOOTER_TEXT


def generate_groups_summary_excel(classroom, groups: list, extra: dict) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = 'Group Summary'
    ncols = 7
    headers = ['Group', 'Members', 'Very Strong', 'Strong', 'Average', 'Weak', 'Group Avg %']
    row = _write_xl_header(ws, classroom, extra, 'Group Summary', ncols)

    for i, h in enumerate(headers, start=1):
        c = ws.cell(row, i, h)
        c.font = Font(bold=True, color='FFFFFFFF', size=10)
        c.fill = _fill('FF111827')
        c.alignment = Alignment(horizontal='center')
        c.border = _thin_border()
    row += 1

    def _avg_fill_font(pct):
        if pct is None:
            return None, Font(color='FF6b7280')
        if pct >= 65: return _fill('FFecfdf5'), Font(color='FF10b981', bold=True)
        if pct >= 45: return _fill('FFfffbeb'), Font(color='FFf59e0b', bold=True)
        return _fill('FFfef2f2'), Font(color='FFf43f5e', bold=True)

    TIER_TEXT = {
        'very_strong': 'FF10b981', 'strong': 'FF2563eb', 'average': 'FFf59e0b', 'weak': 'FFf43f5e',
    }
    for r_i, g in enumerate(groups):
        counts = {'very_strong': 0, 'strong': 0, 'average': 0, 'weak': 0}
        avgs = []
        for m in g.memberships.all():
            if m.tier in counts:
                counts[m.tier] += 1
            if m.average_at_placement is not None:
                avgs.append(m.average_at_placement)
        group_avg = round(sum(avgs) / len(avgs), 1) if avgs else None
        values = [g.name, g.memberships.count(), counts['very_strong'], counts['strong'],
                  counts['average'], counts['weak'], f'{group_avg}%' if group_avg is not None else '—']
        # Faint zebra striping using each group's own badge colour, tinted
        # very light, so the whole sheet isn't a wall of black-on-white.
        zebra = _fill('FFF9FAFB') if r_i % 2 else None
        for i, v in enumerate(values, start=1):
            c = ws.cell(row, i, v)
            c.border = _thin_border()
            c.alignment = Alignment(horizontal='center' if i > 1 else 'left')
            if zebra and i not in (3, 4, 5, 6, 7):
                c.fill = zebra
        # Bold group name, and colour each tier-count column to match the
        # same palette used everywhere else in-app.
        ws.cell(row, 1).font = Font(bold=True, color='FF111827')
        for col, tier in zip((3, 4, 5, 6), ('very_strong', 'strong', 'average', 'weak')):
            ws.cell(row, col).font = Font(bold=True, color=TIER_TEXT[tier])
        avg_fill, avg_font = _avg_fill_font(group_avg)
        avg_cell = ws.cell(row, 7)
        avg_cell.font = avg_font
        if avg_fill:
            avg_cell.fill = avg_fill
        row += 1

    row += 1
    _write_xl_footer(ws, row, ncols)

    widths = [26, 12, 14, 12, 12, 10, 14]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_group_work_analytics_excel(classroom, analytics: dict, extra: dict) -> bytes:
    """Three sheets: By Group, By Stream, Trend — the Excel counterpart
    of the Group Work Analytics page, one tab per rollup."""
    wb = Workbook()

    def _pct_fill_font(pct):
        if pct is None:
            return None, Font(color='FF6b7280')
        if pct >= 65: return _fill('FFecfdf5'), Font(color='FF10b981', bold=True)
        if pct >= 45: return _fill('FFfffbeb'), Font(color='FFf59e0b', bold=True)
        return _fill('FFfef2f2'), Font(color='FFf43f5e', bold=True)

    # ── Sheet 1: By Group ────────────────────────────────────────────
    ws = wb.active
    ws.title = 'By Group'
    ncols = 6
    row = _write_xl_header(ws, classroom, extra, 'Group Work Analytics — By Group', ncols)
    headers = ['Group', 'Stream', 'Assignments', 'Best %', 'Worst %', 'Average %']
    for i, h in enumerate(headers, start=1):
        c = ws.cell(row, i, h)
        c.font = Font(bold=True, color='FFFFFFFF', size=10)
        c.fill = _fill('FF111827')
        c.alignment = Alignment(horizontal='center')
        c.border = _thin_border()
    row += 1
    for g in analytics.get('per_group', []):
        values = [g['group_name'], g['stream_name'] or '—', g['assignments_count'],
                  f"{g['best_pct']}%", f"{g['worst_pct']}%", f"{g['average_pct']}%"]
        for i, v in enumerate(values, start=1):
            c = ws.cell(row, i, v)
            c.border = _thin_border()
            c.alignment = Alignment(horizontal='center' if i > 1 else 'left')
        ws.cell(row, 1).font = Font(bold=True, color='FF111827')
        fill, font = _pct_fill_font(g['average_pct'])
        avg_cell = ws.cell(row, 6)
        avg_cell.font = font
        if fill:
            avg_cell.fill = fill
        row += 1
    row += 1
    _write_xl_footer(ws, row, ncols)
    for i, w in enumerate([24, 16, 13, 10, 10, 12], start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    # ── Sheet 2: By Stream ───────────────────────────────────────────
    ws2 = wb.create_sheet('By Stream')
    ncols2 = 4
    row = _write_xl_header(ws2, classroom, extra, 'Group Work Analytics — By Stream', ncols2)
    headers = ['Stream', 'Groups', 'Assignments Scored', 'Average %']
    for i, h in enumerate(headers, start=1):
        c = ws2.cell(row, i, h)
        c.font = Font(bold=True, color='FFFFFFFF', size=10)
        c.fill = _fill('FF111827')
        c.alignment = Alignment(horizontal='center')
        c.border = _thin_border()
    row += 1
    for s in analytics.get('per_stream', []):
        values = [s['stream_name'], s['group_count'], s['assignments_scored'], f"{s['average_pct']}%"]
        for i, v in enumerate(values, start=1):
            c = ws2.cell(row, i, v)
            c.border = _thin_border()
            c.alignment = Alignment(horizontal='center' if i > 1 else 'left')
        ws2.cell(row, 1).font = Font(bold=True, color='FF111827')
        fill, font = _pct_fill_font(s['average_pct'])
        avg_cell = ws2.cell(row, 4)
        avg_cell.font = font
        if fill:
            avg_cell.fill = fill
        row += 1
    row += 1
    _write_xl_footer(ws2, row, ncols2)
    for i, w in enumerate([20, 10, 18, 12], start=1):
        ws2.column_dimensions[get_column_letter(i)].width = w

    # ── Sheet 3: Trend ───────────────────────────────────────────────
    ws3 = wb.create_sheet('Trend')
    ncols3 = 5
    row = _write_xl_header(ws3, classroom, extra, 'Group Work Analytics — Assignment Trend', ncols3)
    headers = ['Date', 'Assignment', 'Type', 'Groups Scored', 'Average %']
    for i, h in enumerate(headers, start=1):
        c = ws3.cell(row, i, h)
        c.font = Font(bold=True, color='FFFFFFFF', size=10)
        c.fill = _fill('FF111827')
        c.alignment = Alignment(horizontal='center')
        c.border = _thin_border()
    row += 1
    for t_row in analytics.get('trend', []):
        values = [t_row['date'], t_row['title'], t_row['assignment_type'],
                  t_row['groups_scored'], f"{t_row['average_pct']}%"]
        for i, v in enumerate(values, start=1):
            c = ws3.cell(row, i, v)
            c.border = _thin_border()
            c.alignment = Alignment(horizontal='center' if i not in (2,) else 'left')
        fill, font = _pct_fill_font(t_row['average_pct'])
        avg_cell = ws3.cell(row, 5)
        avg_cell.font = font
        if fill:
            avg_cell.fill = fill
        row += 1
    row += 1
    _write_xl_footer(ws3, row, ncols3)
    for i, w in enumerate([14, 30, 14, 15, 12], start=1):
        ws3.column_dimensions[get_column_letter(i)].width = w

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_groups_roster_excel(classroom, groups: list, extra: dict) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = 'Group Rosters'
    ncols = 5
    row = _write_xl_header(ws, classroom, extra, 'Group Rosters & Scores', ncols)

    for g in groups:
        # Group banner row, with badge image if available.
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
        title = g.name + (f'  ·  {g.subject.name}' if g.subject_id else '')
        c = ws.cell(row, 1, title)
        c.font = Font(bold=True, color='FFFFFFFF', size=12)
        c.fill = _fill(g.badge_color.replace('#', 'FF') if g.badge_color else 'FF2563eb')
        c.alignment = Alignment(horizontal='left', indent=2)
        ws.row_dimensions[row].height = 24
        badge_path = _badge_path(g)
        if badge_path:
            try:
                img = XLImage(badge_path)
                img.height, img.width = 28, 28
                img.anchor = f'A{row}'
                ws.add_image(img)
            except Exception:
                pass
        row += 1

        headers = ['#', 'Student Name', 'Student ID', 'Tier', 'Score %']
        for i, h in enumerate(headers, start=1):
            c = ws.cell(row, i, h)
            c.font = Font(bold=True, size=9, color='FFFFFFFF')
            c.fill = _fill('FF374151')
            c.border = _thin_border()
            c.alignment = Alignment(horizontal='center')
        row += 1

        members = sorted(g.memberships.all(), key=lambda m: -(m.average_at_placement or 0))
        if not members:
            ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=ncols)
            ws.cell(row, 1, 'No members yet').alignment = Alignment(horizontal='center')
            row += 1
        for i, m in enumerate(members, start=1):
            values = [i, m.student.full_name, m.student.student_id,
                      TIER_LABELS.get(m.tier, m.tier),
                      f'{m.average_at_placement}%' if m.average_at_placement is not None else '—']
            for col, v in enumerate(values, start=1):
                c = ws.cell(row, col, v)
                c.border = _thin_border()
                c.alignment = Alignment(horizontal='center' if col != 2 else 'left')
                if col == 4:
                    c.fill = _fill(TIER_COLORS_XL.get(m.tier, 'FFFFFFFF'))
                    c.font = Font(color='FFFFFFFF', bold=True, size=9)
            row += 1
        row += 1  # blank row between groups

    _write_xl_footer(ws, row, ncols)

    widths = [5, 26, 14, 16, 12]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
