# Generated by Django 5.2.8 on 2026-07-28 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[
                    ('at_risk', 'Student At-Risk Alert'),
                    ('risk_critical', 'Critical Risk Score'),
                    ('exam_published', 'Exam Published'),
                    ('integrity_flag', 'Grade Integrity Flag'),
                    ('daily_digest', 'Daily Digest'),
                    ('test', 'Test Email'),
                ], max_length=30)),
                ('frequency', models.CharField(choices=[
                    ('immediate', 'Send immediately'),
                    ('digest', 'Include in daily digest'),
                    ('off', 'Turn off'),
                ], default='immediate', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'notification_preferences'},
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[
                    ('at_risk', 'Student At-Risk Alert'),
                    ('risk_critical', 'Critical Risk Score'),
                    ('exam_published', 'Exam Published'),
                    ('integrity_flag', 'Grade Integrity Flag'),
                    ('daily_digest', 'Daily Digest'),
                    ('test', 'Test Email'),
                ], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, help_text='One-line plain-text summary for the in-app list', max_length=500)),
                ('related_object_type', models.CharField(blank=True, max_length=30)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                    ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (preference off)'),
                ], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'notification_logs', 'ordering': ['-sent_at']},
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'category')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'sent_at'], name='notif_log_recipient_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['category', 'related_object_type', 'related_object_id', 'sent_at'], name='notif_log_dedupe_idx'),
        ),
    ]
