# Generated by Django 5.0.6 on 2026-08-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('students', '0003_stream_studentprofile_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(default=list, help_text='Raw email addresses the report was sent to')),
                ('report_type', models.CharField(choices=[('overview', 'Platform Overview'), ('at-risk', 'At-Risk Students'), ('class', 'Class Performance')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_report_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
