# Generated by Django 5.0.6 on 2026-08-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_analyticsreportlog'),
        ('students', '0003_stream_studentprofile_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreportlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_reports', to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='analyticsreportlog',
            name='report_type',
            field=models.CharField(choices=[('overview', 'Platform Overview'), ('at-risk', 'At-Risk Students'), ('class', 'Class Performance'), ('student', 'Individual Student')], max_length=20),
        ),
    ]
