# Generated by Django 5.0.6 on 2026-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_analyticsreportlog_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
