# Generated by Django 5.0.6 on 2026-08-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationlog_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='category',
            field=models.CharField(choices=[('at_risk', 'Student At-Risk Alert'), ('risk_critical', 'Critical Risk Score'), ('exam_published', 'Exam Published'), ('integrity_flag', 'Grade Integrity Flag'), ('daily_digest', 'Daily Digest'), ('tournament_result', 'Tournament Result'), ('test', 'Test Email')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('at_risk', 'Student At-Risk Alert'), ('risk_critical', 'Critical Risk Score'), ('exam_published', 'Exam Published'), ('integrity_flag', 'Grade Integrity Flag'), ('daily_digest', 'Daily Digest'), ('tournament_result', 'Tournament Result'), ('test', 'Test Email')], max_length=30),
        ),
    ]
