# Generated by Django 4.2.16 on 2026-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='index_number',
            field=models.CharField(blank=True, help_text='NECTA examination index number', max_length=30),
        ),
    ]
