# Generated by Django 5.0.6 on 2026-08-15 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_stream_studentprofile_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_percentage',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Student's self-set target average percentage (1-100).", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
